from gym_additions.envs.gridworld_env import GridworldEnv   # noqa
from gym_additions.envs.windy_gridworld_env import *    # noqa
from gym_additions.envs.cliff_env import CliffEnv   # noqa
from gym_additions.envs.tictactoe_env import TicTacToeEnv   # noqa
from gym_additions.envs.cross6_env import Cross6Env    # noqa
from gym_additions.envs.coinflip_env import CoinFlipEnv    # noqa
from gym_additions.envs.racetrack_env import *    # noqa
from gym_additions.envs.randomwalk_env import RandomWalkEnv    # noqa
from gym_additions.envs.maxbias_env import MaxBiasEnv    # noqa
from gym_additions.envs.dynamaze_env import *    # noqa
from gym_additions.envs.cartpole_env import *    # noqa
from gym_additions.envs.acrobot_env import *    # noqa
from gym_additions.envs.fourrooms_env import *    # noqa
from gym_additions.envs.mountaincar_env import *    # noqa
from gym_additions.envs.shortcorridor_env import *    # noqa
from gym_additions.envs.localmin_env import *    # noqa
from gym_additions.envs.tractor_env import *    # noqa
