from gym.envs.registration import register

register(
    id='Gridworld-v0',
    entry_point='gym_additions.envs:GridworldEnv',
    )
register(
    id='WindyGridworld-v0',
    entry_point='gym_additions.envs:WindyGridworldEnv',
    )
register(
    id='WindyGridworld-v1',
    entry_point='gym_additions.envs:WindyGridworldKingEnv',
    )
register(
    id='WindyGridworld-v2',
    entry_point='gym_additions.envs:WindyGridworldStochaEnv',
    )
register(
    id='Cliff-v0',
    entry_point='gym_additions.envs:CliffEnv',
    )
register(
    id='TicTacToe-v0',
    entry_point='gym_additions.envs:TicTacToeEnv',
    )
register(
    id='Cross6-v0',
    entry_point='gym_additions.envs:Cross6Env',
    )
register(
    id='CoinFlip-v0',
    entry_point='gym_additions.envs:CoinFlipEnv',
    )
register(
    id='RaceTrack-v0',
    entry_point='gym_additions.envs:RaceTrackEnv',
    )
register(
    id='RaceTrack-v1',
    entry_point='gym_additions.envs:RaceTrackPunishEnv',
    )
register(
    id='RandomWalk-v0',
    entry_point='gym_additions.envs:RandomWalkEnv',
    )
register(
    id='MaxBias-v0',
    entry_point='gym_additions.envs:MaxBiasEnv',
    )
register(
    id='DynaMaze-v0',
    entry_point='gym_additions.envs:DynaMazeEnv',
    )
register(
    id='BlockingMaze-v0',
    entry_point='gym_additions.envs:BlockingMazeEnv',
    )
register(
    id='ShortcutMaze-v0',
    entry_point='gym_additions.envs:ShortcutMazeEnv',
    )
register(
    id='ShortcutBlockMaze-v0',
    entry_point='gym_additions.envs:ShortcutBlockMazeEnv',
    )
register(
    id='CartPole-v2',
    entry_point='gym_additions.envs:CartPoleTileEnv',
    )
register(
    id='CartPole-v3',
    entry_point='gym_additions.envs:CartPolePolyEnv',
    )
register(
    id='CartPole-v4',
    entry_point='gym_additions.envs:CartPoleDoubleEnv',
    )
register(
    id='Acrobot-v2',
    entry_point='gym_additions.envs:AcrobotTileEnv',
    )
register(
    id='Acrobot-v3',
    entry_point='gym_additions.envs:AcrobotPolyEnv',
    )
register(
    id='Acrobot-v4',
    entry_point='gym_additions.envs:AcrobotDoubleEnv',
    )
register(
    id='FourRooms-v0',
    entry_point='gym_additions.envs:FourRoomsEnv',
    )
register(
    id='FourRoomsMin-v0',
    entry_point='gym_additions.envs:FourRoomsMinEnv',
    )
register(
    id='FourRoomsGoal-v0',
    entry_point='gym_additions.envs:FourRoomsGoalEnv',
    )
register(
    id='FourRoomsGoalBig-v0',
    entry_point='gym_additions.envs:FourRoomsGoalBigEnv',
    )
register(
    id='MountainCar-v2',
    entry_point='gym_additions.envs:MountainCarTileEnv',
    )
register(
    id='MountainCar-v3',
    entry_point='gym_additions.envs:MountainCarPolyEnv',
    )
register(
    id='MountainCar-v4',
    entry_point='gym_additions.envs:MountainCarDoubleEnv',
    )
register(
    id='ShortCorridor-v0',
    entry_point='gym_additions.envs:ShortCorridorEnv',
    )
register(
    id='LocalMin-v0',
    entry_point='gym_additions.envs:LocalMinEnv',
    )
register(
    id='Tractor-v0',
    entry_point='gym_additions.envs:TractorEnv',
    )
