from gym.envs.registration import register

register(
    id='Gridworld-v0',
    entry_point='gym_additions.envs:GridworldEnv',
    )
register(
    id='WindyGridworld-v0',
    entry_point='gym_additions.envs:WindyGridworldEnv',
    )
register(
    id='WindyGridworld-v1',
    entry_point='gym_additions.envs:WindyGridworldKingEnv',
    )
register(
    id='WindyGridworld-v2',
    entry_point='gym_additions.envs:WindyGridworldStochaEnv',
    )
register(
    id='Cliff-v0',
    entry_point='gym_additions.envs:CliffEnv',
    )
register(
    id='TicTacToe-v0',
    entry_point='gym_additions.envs:TicTacToeEnv',
    )
register(
    id='Cross6-v0',
    entry_point='gym_additions.envs:Cross6Env',
    )
register(
    id='CoinFlip-v0',
    entry_point='gym_additions.envs:CoinFlipEnv',
    )
register(
    id='RaceTrack-v0',
    entry_point='gym_additions.envs:RaceTrackEnv',
    )
register(
    id='RaceTrack-v1',
    entry_point='gym_additions.envs:RaceTrackPunishEnv',
    )
register(
    id='RandomWalk-v0',
    entry_point='gym_additions.envs:RandomWalkEnv',
    )
register(
    id='MaxBias-v0',
    entry_point='gym_additions.envs:MaxBiasEnv',
    )
register(
    id='DynaMaze-v0',
    entry_point='gym_additions.envs:DynaMazeEnv',
    )
register(
    id='BlockingMaze-v0',
    entry_point='gym_additions.envs:BlockingMazeEnv',
    )
register(
    id='ShortcutMaze-v0',
    entry_point='gym_additions.envs:ShortcutMazeEnv',
    )
register(
    id='CartPole-v2',
    entry_point='gym_additions.envs:CartPoleTileEnv',
    )
register(
    id='Acrobot-v2',
    entry_point='gym_additions.envs:AcrobotTileEnv',
    )
register(
    id='FourRooms-v0',
    entry_point='gym_additions.envs:FourRoomsEnv',
    )
